eureka:
  client:
    service-url:
#      defaultZone: http://121.196.146.187:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: admin-gateway
  cloud:
    #    gateway配置
    gateway:
      routes:
        - id: apartment_admin_route
          #          uri: lb://admin
          uri: http://localhost:18081
          predicates:
            - Path=/admin/**,/position/**,/adminGrade/**,/adminInfo/**

        - id: apartment_good_route
          #          uri: lb://good
          uri: http://localhost:18083
          predicates:
            - Path=/category/**,/brand/**,/categoryBrand/**,/powerprice/**,/sku/**,/spec/**,/template/**

        - id: apartment_order_route
          #          uri: lb://order
          uri: http://localhost:18084
          predicates:
            - Path=/order/**,/orderInfo/**

        - id: apartment_require_route
          #          uri: lb://require
          uri: http://localhost:18085
          predicates:
            - Path=/require/**

        - id: apartment_room_route
          #          uri: lb://room
          uri: http://localhost:18086
          predicates:
            - Path=/room/**

        - id: apartment_user_route   # 唯一标识符,可以任意选取
          #  指定路由网址
          #          uri: lb://user
          uri: http://localhost:18087
          predicates:
            # 所有以/user开头的请求都将路由到http://121.196.146.187:18087
            # 例如  121.196.146.187:8001/user  ——>  121.196.146.187:18081/user
            - Path=/user/**

        - id: apartment_webSearch_route
          uri: http://localhost:18090
          predicates:
            - Path=/goodManage/**

        - id: apartment_message_route
          uri: http://localhost:18091
          predicates:
            - Path=/message/**

server:
  port: 8081
feign:
  hystrix:
    enabled: true