eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
server:
  port: 18089
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: canal
canal:
  client:
    instances:
      example:
        host: 42.194.148.173
        port: 11111
feign:
  hystrix:
    enabled: false
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000