eureka:
  client:
    service-url:
#      defaultZone: http://121.196.146.187:7001/eureka
        defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: good
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.146.187:3306/apartment_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&wait_timeout=86400
    username: hxj
    password: HXJ010425.
    hikari:
      max-lifetime: 180000
  main:
    allow-bean-definition-overriding: true
  jetty:
    accesslog:
      time-zone: Asia/Shanghai
feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 1500
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
snowflake:
  conf:
    workerId: 1
    datacenterId: 1
server:
  port: 18083
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: hxj.apartment.bean