eureka:
  client:
    service-url:
      defaultZone: http://121.196.146.187:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  thymeleaf:
    #构建URL时预先查看名称的前缀，默认就是这个，写在这里是怕忘了怎么配置
    prefix: classpath:/templates/
    suffix: .html   #后缀
    cache: false    #禁止缓存
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.146.187:3306/apartment_admins?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&wait_timeout=86400
    username: hxj
    password: HXJ010425.
    hikari:
      max-lifetime: 180000
server:
  port: 18081
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 1500
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
#前端信息
frontServer:
  ip: 127.0.0.1
  port: 80
  road: /后台/