eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 42.194.148.173:9300
server:
  port: 18088
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 150000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 900000
#ribbon的超时时间
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
