eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 42.194.148.173:9300

  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: false
  httpclient:
    connection-timeout: 150000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 900000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
server:
  port: 18088