eureka:
  client:
    service-url:
      defaultZone: http://121.196.146.187:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: require
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.146.187:3306/apartment_requires?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&wait_timeout=86400
    username: hxj
    password: HXJ010425.
server:
  port: 18085
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 1500
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
